### ISSUE TITLE
Feature Request: ARM Support

### ISSUE THREAD

**Issue by kmf** [sensu/monitoring-plugins#27] opened 2021-08-29 07:31 UTC
Hi there

ARM support would be awesome

**Comment by asachs01** [comment] 2022-05-04 21:01
Hey there, this seems to be a duplicate of #3 . I'll close this out for now, but if you feel like there's something substantively different from the issue I mentioned, feel free to reopen this.

**Closed by asachs01** 2022-05-04 21:01 UTC

**Comment by elfranne** [comment] 2022-07-27 21:23
@kmf  see #39
